In [32]:
import numpy as np
import pandas as pd

### Data Processing

In [33]:
patients = pd.read_csv('patients.csv')
diagnoses = pd.read_csv('diagnoses.csv')
outcomes = pd.read_csv('outcomes.csv')
labs = pd.read_csv('labs.csv')

In [34]:
patients

,PatientID,Name,Age,Gender,DiagnosisID,AdmissionDate,DischargeDate,OutcomeID,TreatmentCost
0,1,Edward Montes,68,M,2,2025-03-22,2025-04-04,1,4443
1,2,Jessica Zimmerman,81,M,2,2025-03-31,2025-04-02,2,4265
2,3,Gina Alexander,58,M,6,2025-01-08,2025-03-13,1,4188
3,4,Lori Green,44,F,3,2025-04-03,2025-04-05,1,9783
4,5,Jack Logan,72,F,9,2025-06-03,2025-06-04,1,5005
...,...,...,...,...,...,...,...,...,...
195,196,Shelly Dominguez,72,M,10,2025-04-28,2025-05-02,3,3311
196,197,Destiny Johnson,58,M,2,2025-03-06,2025-07-08,3,5191
197,198,Catherine Case,65,M,3,2025-05-26,2025-06-04,2,8957
198,199,Dennis Wolfe,42,F,2,2025-06-26,2025-07-05,2,4538
199,200,Gregory Bates,61,F,3,2025-01-11,2025-03-09,3,5983

In [35]:
diagnoses

   DiagnosisID   DiagnosisName
0            1    Hypertension
1            2        Diabetes
2            3   Heart Disease
3            4          Asthma
4            5          Stroke
5            6            COPD
6            7          Cancer
7            8       Arthritis
8            9  Kidney Disease
9           10   Liver Disease

In [36]:
outcomes

   OutcomeID  OutcomeName
0          1    Recovered
1          2  Complicated
2          3     Deceased

In [37]:
labs

     LabID  PatientID        TestName  Result NormalRange
0        1        196  Blood Pressure    89.7     150-200
1        2        165     Cholesterol   270.2       13-17
2        3        182  Blood Pressure   268.0     0.6-1.2
3        4        142     Cholesterol    57.3     150-200
4        5         55     Blood Sugar   256.5      120/80
..     ...        ...             ...     ...         ...
195    196        176     Cholesterol   194.7      70-120
196    197         72      Hemoglobin   159.7       20-50
197    198         59  Blood Pressure   231.3      70-120
198    199         82      Creatinine   171.7       13-17
199    200        116      Hemoglobin   268.4     150-200

[200 rows x 5 columns]

### EDA

In [38]:
patients.shape

(200, 9)

In [39]:
patients.columns

Index(['PatientID', 'Name', 'Age', 'Gender', 'DiagnosisID', 'AdmissionDate',
       'DischargeDate', 'OutcomeID', 'TreatmentCost'],
      dtype='object')

In [40]:
patients.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 9 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   PatientID      200 non-null    int64
 1   Name           200 non-null    object
 2   Age            200 non-null    int64
 3   Gender         200 non-null    object
 4   DiagnosisID    200 non-null    int64
 5   AdmissionDate  200 non-null    object
 6   DischargeDate  200 non-null    object
 7   OutcomeID      200 non-null    int64
 8   TreatmentCost  200 non-null    int64
dtypes: int64(5), object(4)
memory usage: 14.2+ KB

In [41]:
patients.describe()

        PatientID        Age  DiagnosisID   OutcomeID  TreatmentCost
count  200.000000  200.00000   200.000000  200.000000     200.000000
mean   100.500000   59.32500     5.245000    2.030000    6104.910000
std     57.879185   17.39027     2.971384    0.813887    2201.939376
min      1.000000   30.00000     1.000000    1.000000    2054.000000
25%     50.750000   44.00000     3.000000    1.000000    4415.250000
50%    100.500000   58.50000     5.000000    2.000000    5929.500000
75%    150.250000   73.00000     8.000000    3.000000    7963.000000
max    200.000000   89.00000    10.000000    3.000000    9973.000000

In [42]:
patients.isna().sum()

PatientID        0
Name             0
Age              0
Gender           0
DiagnosisID      0
AdmissionDate    0
DischargeDate    0
OutcomeID        0
TreatmentCost    0
dtype: int64

In [43]:
patients[patients.duplicated()]

Empty DataFrame
Columns: [PatientID, Name, Age, Gender, DiagnosisID, AdmissionDate, DischargeDate, OutcomeID, TreatmentCost]
Index: []

In [44]:
patients = patients.merge(diagnoses, on='DiagnosisID')
patients = patients.merge(outcomes, on='OutcomeID')

In [45]:
patients.head(5)

,PatientID,Name,Age,Gender,DiagnosisID,AdmissionDate,DischargeDate,OutcomeID,TreatmentCost,DiagnosisName,OutcomeName
0,1,Edward Montes,68,M,2,2025-03-22,2025-04-04,1,4443,Diabetes,Recovered
1,2,Jessica Zimmerman,81,M,2,2025-03-31,2025-04-02,2,4265,Diabetes,Complicated
2,3,Gina Alexander,58,M,6,2025-01-08,2025-03-13,1,4188,COPD,Recovered
3,4,Lori Green,44,F,3,2025-04-03,2025-04-05,1,9783,Heart Disease,Recovered
4,5,Jack Logan,72,F,9,2025-06-03,2025-06-04,1,5005,Kidney Disease,Recovered

In [46]:
patients['AdmissionDate'] = pd.to_datetime(patients['AdmissionDate'])
patients['DischargeDate'] = pd.to_datetime(patients['DischargeDate'])

In [47]:
patients['AdmissionDate'].head(5)

0   2025-03-22
1   2025-03-31
2   2025-01-08
3   2025-04-03
4   2025-06-03
Name: AdmissionDate, dtype: datetime64[ns]

In [48]:
patients['DischargeDate'].tail(5)

195   2025-05-02
196   2025-07-08
197   2025-06-04
198   2025-07-05
199   2025-03-09
Name: DischargeDate, dtype: datetime64[ns]

In [49]:
patients['Length_of_Stay'] = (patients['DischargeDate'] - patients['AdmissionDate']).dt.days

In [50]:
patients['Length_of_Stay'].head(5)

0    13
1     2
2    64
3     2
4     1
Name: Length_of_Stay, dtype: int64

### Feature Engineering

In [51]:
patients['OutcomeName']

0        Recovered
1      Complicated
2        Recovered
3        Recovered
4        Recovered
          ...
195       Deceased
196       Deceased
197    Complicated
198    Complicated
199       Deceased
Name: OutcomeName, Length: 200, dtype: object

In [52]:
patients['OutcomeEncoded'] = patients['OutcomeName'].map({'Recovered' : 0, 'Complicated' : 1, 'Deceased' : 1})

In [53]:
patients['OutcomeEncoded'].head(10)

0    0
1    1
2    0
3    0
4    0
5    0
6    1
7    0
8    1
9    1
Name: OutcomeEncoded, dtype: int64

- Creating Risk Indicator

In [54]:
patients['HighRisk'] = np.where((patients['Age'] > 65) | (patients['OutcomeName'].isin(['Complicated', 'Deceased'])), 1,0)

In [55]:
patients['HighRisk']

0      1
1      1
2      0
3      0
4      1
      ..
195    1
196    1
197    1
198    1
199    1
Name: HighRisk, Length: 200, dtype: int64

In [ ]:
abnormal_conditions = {
    'Blood Sugar': lambda x: x > 120,
    'Cholesterol': lambda x: x > 200,
    'Hemoglobin': lambda x: x < 13,
}

def count_abnormal_labs_results(patient_id):
    patient_labs = labs[labs['PatientID'] == patient_id]
    count = 0
    for test_name, condition in abnormal_conditions.items():
        test_results = patient_labs[patient_labs['TestName'] == test_name]
        count += test_results['Result'].apply(condition).sum()
    return count

patients['AbnormalLabCount'] = patients['PatientID'].apply(count_abnormal_labs_results)

In [59]:
patients[['PatientID', 'AbnormalLabCount']].head(10)

   PatientID  AbnormalLabCount
0          1               0.0
1          2               1.0
2          3               0.0
3          4               0.0
4          5               0.0
5          6               0.0
6          7               0.0
7          8               0.0
8          9               0.0
9         10               0.0

In [60]:
patients[patients['AbnormalLabCount'] == 2]

,PatientID,Name,Age,Gender,DiagnosisID,AdmissionDate,DischargeDate,OutcomeID,TreatmentCost,DiagnosisName,OutcomeName,Length_of_Stay,OutcomeEncoded,HighRisk,AbnormalLabCount
13,14,Cody Ryan,53,F,7,2025-06-06,2025-06-10,2,9147,Cancer,Complicated,4,1,1,2.0
16,17,Sabrina Medina,69,F,1,2025-01-21,2025-05-22,3,7443,Hypertension,Deceased,121,1,1,2.0
28,29,Katherine Gonzales,50,M,1,2025-01-12,2025-01-14,3,7109,Hypertension,Deceased,2,1,1,2.0
35,36,Beverly Dillon,78,M,1,2025-01-17,2025-04-11,2,8922,Hypertension,Complicated,84,1,1,2.0
164,165,Michael Warren,66,M,10,2025-04-27,2025-05-01,2,2054,Liver Disease,Complicated,4,1,1,2.0